<a href="https://colab.research.google.com/github/amitsingh6261/my_all_python_Program/blob/main/ecommerce_sales_customer_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 # Part 1 — Customers

Q1. Total customers kitne hain?

Q2. City-wise customers ki count nikalo.

Q3. Gender-wise customers ki count nikalo.

Q4. Customers ki average age kya hai?

Q5. Kaunsi city me sabse zyada customers hain?

In [1]:
import pandas as pd

In [2]:
ct=pd.read_csv("/content/customers.csv")
ct.head(5)

,customer_id,customer_name,email,gender,age,city,state,signup_date
0,CUST1001,Rohan Mehta,rohan.mehta13@example.com,Male,57,Chennai,Tamil Nadu,2024-03-12
1,CUST1002,Neha Mehta,neha.mehta96@example.com,Male,47,Jaipur,Rajasthan,2024-08-04
2,CUST1003,Vivaan Sharma,vivaan.sharma21@example.com,Male,33,Hyderabad,Telangana,2024-11-04
3,CUST1004,Aarav Bhatia,aarav.bhatia35@example.com,Male,61,Jaipur,Rajasthan,2024-08-17
4,CUST1005,Riya Nair,riya.nair10@example.com,Female,26,Bengaluru,Karnataka,2024-06-23

In [3]:
od=pd.read_csv("/content/orders.csv")
od.head(5)

,order_id,order_date,customer_id,product_id,quantity,discount_percent,total_amount,order_status
0,ORD20001,2024-09-18,CUST1001,PROD1001,1,5,3609.05,Shipped
1,ORD20002,2024-09-14,CUST1002,PROD1002,3,0,7047.00,Returned
2,ORD20003,2025-03-22,CUST1003,PROD1003,1,0,1699.00,Delivered
3,ORD20004,2025-01-01,CUST1004,PROD1004,1,10,2249.10,Delivered
4,ORD20005,2024-10-18,CUST1005,PROD1005,1,0,1549.00,Returned

In [4]:
pt=pd.read_csv("/content/products.csv")
pt.head(5)

,product_id,product_name,category,brand,unit_price,cost_price,stock_quantity,rating
0,PROD1001,Samsung Wireless Headphones v1,Electronics,Samsung,3799.0,2420.0,112,3.8
1,PROD1002,Nike Smartwatch Fit v1,Electronics,Nike,2349.0,1680.0,40,3.7
2,PROD1003,Apple Gaming Mouse v1,Electronics,Apple,1699.0,740.0,94,4.1
3,PROD1004,Boat Bluetooth Speaker v1,Electronics,Boat,2499.0,1020.0,123,4.5
4,PROD1005,Ikea Cotton Casual Shirt v1,Fashion,Ikea,1549.0,410.0,21,4.5

In [5]:
total_customers=ct['customer_id'].nunique()
print("total_customer", total_customers)

total_customer 100

In [6]:
city_customers=ct['city'].value_counts()
print("city_customers",city_customers)

city_customers city
Pune         13
Hyderabad    12
Lucknow      11
Chennai      10
Delhi        10
Kolkata      10
Jaipur        9
Bengaluru     9
Ahmedabad     9
Mumbai        7
Name: count, dtype: int64

In [7]:
Gender_customers=ct['gender'].value_counts()
print("Gender_customers",Gender_customers)

Gender_customers gender
Male      58
Female    42
Name: count, dtype: int64

In [8]:
Average_age=ct['age'].mean()
print("Average_age",round(Average_age,2))

Average_age 39.27

In [9]:
maximum_customers=ct['city'].max()
print("maximum_customers",maximum_customers)

maximum_customers Pune

# Part 2 — Products

Q6. Total products kitne hain aur category-wise products kitne hain?

Q7. Har category ka average product price nikalo.

Q8. Top 5 most expensive products nikalo.

Q9. Kis category ke products ka average price sabse zyada hai?

In [10]:
total_products=pt['product_id'].nunique()
print("total_products", total_products)

total_products 100

In [11]:
category_wise_product=pt['category'].value_counts()
print("category_wise_product",category_wise_product)

category_wise_product category
Electronics       34
Fashion           20
Home & Kitchen    20
Footwear           7
Furniture          7
Sports             6
Beauty             6
Name: count, dtype: int64

In [12]:
pt.groupby('category')['cost_price'].mean()

category
Beauty             176.666667
Electronics       1514.705882
Fashion            695.000000
Footwear          1720.000000
Furniture         4851.428571
Home & Kitchen     410.500000
Sports             293.333333
Name: cost_price, dtype: float64

In [13]:
most_expensive_products=pt.sort_values('cost_price',ascending=False).head(5)
most_expensive_products

,product_id,product_name,category,brand,unit_price,cost_price,stock_quantity,rating
97,PROD1098,Sony Ergonomic Desk Chair v7,Furniture,Sony,7299.0,5080.0,189,4.6
7,PROD1008,Sony Ergonomic Desk Chair v1,Furniture,Sony,7549.0,4920.0,68,4.2
67,PROD1068,Sony Ergonomic Desk Chair v5,Furniture,Sony,7749.0,4920.0,79,3.9
52,PROD1053,Apple Ergonomic Desk Chair v4,Furniture,Apple,7799.0,4880.0,100,3.9
22,PROD1023,Apple Ergonomic Desk Chair v2,Furniture,Apple,7699.0,4760.0,43,4.0

In [14]:
Avg_price=pt.groupby('category')['unit_price'].mean()
top_category=Avg_price.idxmax()
print("Highest Average Price Category: ",top_category)

Highest Average Price Category:  Furniture

# Part 3 — Orders

Q10. Total orders kitne hain?

Q11. Delivered, Cancelled, Returned aur Pending orders ki count nikalo.

Q12. Payment method ke according orders ki count nikalo.

Q13. Har product ki total quantity kitni sell hui?

In [15]:
od.columns

Index(['order_id', 'order_date', 'customer_id', 'product_id', 'quantity',
       'discount_percent', 'total_amount', 'order_status'],
      dtype='object')

In [16]:
Total_orders=od['order_id'].nunique()
print("Total_orders",Total_orders)

Total_orders 100

In [24]:
order_status=od['order_status'].value_counts()
print("order_status: ",order_status)

order_status:  order_status
Delivered    54
Returned     17
Cancelled    15
Shipped      14
Name: count, dtype: int64

In [25]:
total_amount=od['total_amount'].value_counts()
print('total_amount',total_amount)

total_amount total_amount
 989.10      2
 1233.10     2
 5397.00     2
 331.55      2
 898.20      2
            ..
 5898.00     1
-80.80       1
 24816.60    1
 399.00      1
 1399.00     1
Name: count, Length: 94, dtype: int64

In [34]:
quantity=od.groupby('product_id')['quantity'].sum()
print(quantity)

product_id
PROD1001    1
PROD1002    3
PROD1003    1
PROD1004    1
PROD1005    1
           ..
PROD1096    2
PROD1097    1
PROD1098    4
PROD1099    1
PROD1100    1
Name: quantity, Length: 100, dtype: int64

# Part 4 —  Business Analysis

Pehle orders ko customers aur products ke saath merge() karo

In [40]:
final=od.merge(ct,on='customer_id',how='left')
final.head(5)

,order_id,order_date,customer_id,product_id,quantity,discount_percent,total_amount,order_status,customer_name,email,gender,age,city,state,signup_date
0,ORD20001,2024-09-18,CUST1001,PROD1001,1,5,3609.05,Shipped,Rohan Mehta,rohan.mehta13@example.com,Male,57,Chennai,Tamil Nadu,2024-03-12
1,ORD20002,2024-09-14,CUST1002,PROD1002,3,0,7047.00,Returned,Neha Mehta,neha.mehta96@example.com,Male,47,Jaipur,Rajasthan,2024-08-04
2,ORD20003,2025-03-22,CUST1003,PROD1003,1,0,1699.00,Delivered,Vivaan Sharma,vivaan.sharma21@example.com,Male,33,Hyderabad,Telangana,2024-11-04
3,ORD20004,2025-01-01,CUST1004,PROD1004,1,10,2249.10,Delivered,Aarav Bhatia,aarav.bhatia35@example.com,Male,61,Jaipur,Rajasthan,2024-08-17
4,ORD20005,2024-10-18,CUST1005,PROD1005,1,0,1549.00,Returned,Riya Nair,riya.nair10@example.com,Female,26,Bengaluru,Karnataka,2024-06-23

In [42]:
pt.columns

Index(['product_id', 'product_name', 'category', 'brand', 'unit_price',
       'cost_price', 'stock_quantity', 'rating'],
      dtype='object')

In [ ]:
final=pt.merge(final,on='product_id',how='left')